name: master test
on:
  push:
    branches:
      - container-base-ope

env:
    REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
        run: |
          pip install -r requirements/requirements.txt
            
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          start=$(date +%s) #start the timer
          time make build --silent 
          end=$(date +%s) #end timer
          seconds=$((end-start))  #calc build time in sec
          elapsed=$(echo "scale=2; ($end - $start) / 60.0" | bc) #get time in min with dec
          min=${elapsed%.*}  #extract min part 
          sec_cut=${elapsed#*.} #get the decimal 
          sec_round="${sec_cut:0:1}.${sec_cut:1}"
          sec=$( echo "$sec_round * 6" | bc -l) #calc sec's
          echo "BUILD TIME:  $min MIN $sec SECS  or  $seconds seconds" > ./time.txt #send to file for use in diff run
          IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | head -n 1) #get built image
          echo "Image = $IMAGE"
          echo $IMAGE > ./image.txt   

      - name: Push beta version
        run: |
          REGISTRY=$(cat base/ope_book_registry)
          REGISTRY_USER=$(cat base/ope_book_user)
          echo $REGISTRY $REGISTRY_USER
          docker login $REGISTRY -u $REGISTRY_USER -p $REGISTRY_PASSWORD
          make push
      
      - name: upload image
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: |
            image.txt


      - name: upload time
        uses: actions/upload-artifact@v2
        with:
          name: time
          path: |
            time.txt
      

  health-check:
    needs: setup-and-build
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: image

      - name: pull image
        run: |
          IMAGE=$(cat image.txt)
          docker pull $IMAGE

      - name: check-container-health
        run: |
          docker images -a
          IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | head -n 1) #get built image
          echo "image = $IMAGE "
          IM=$(cat image.txt)
          docker run -d --name stable $IM
          sleep 7 #wait to start to check health
          docker ps -a
          CONTAINER_NAME="stable"
          HEALTH=$(docker ps --format "{{.Names}}: {{.Status}}" | grep "$CONTAINER_NAME" | awk '{print $2}') #extract health status
          echo ""
          if [[ "$HEALTH" == "Up" ]]; then
          echo "HEALTHY : container is up and running"
          else
          echo "ERROR : container is not running"
          exit -1
          fi
          echo ""
          docker stop stable

  image-version-check:
    needs: setup-and-build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: image

      - name: pull image
        run: |
          IMAGE=$(cat image.txt)
          docker pull $IMAGE

      - name: check-container-health
        run: |

          IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | head -n 1) #get just built image
          echo "IMAGE = $IMAGE"
          docker run -d --name stable $IMAGE
          ID=$( docker ps -aqf "name=stable" )     #get id of image
          docker inspect $IMAGE > image.json #right inspect info to json for parsing
          REPO_TAG=$(jq -r '.[0].RepoTags[0]' image.json) #acquire tag
          if [[ "$REPO_TAG" == "$IMAGE" ]]; then
                echo "CORRECT IMAGE AND VERSION"
          else
                echo "INCORRECT IMAGE or VERSION, $REPO_TAG is not the proper image $IMAGE"
                exit -1
          fi

  jupnb-test:
    needs: setup-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: image

      - name: pull image
        run: |
          IMAGE=$(cat image.txt)
          docker pull $IMAGE
      - name: run container
        run: |
          IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | head -n 1)
          docker run -d -p 8888:8888 --name stable -v /test.ipynb:/home/jovyan/work $IMAGE
          container_id=$(docker ps -qf "name=stable" | head -n 1)
          docker cp tests/test.ipynb $container_id:/home/jovyan/work #mount test nb into container
      - name: Wait for container to start
        run: |
          until docker exec stable jupyter lab --version; do sleep 1; done
      - name: Execute Notebook
        run: |
          container_id=$(docker ps -qf "name=stable" | head -n 1)
          echo $container_id
          docker exec $container_id jupyter lab --generate-config
          docker exec $container_id sh -c "echo 'c.NotebookApp.token = \"\"' >> /home/jovyan/.jupyter/jupyter_notebook_config.py" #create it without a token
          docker exec $container_id jupyter labextension install @jupyter-widgets/jupyterlab-manager #install widgets
          docker exec $container_id pip install nbclient
          docker exec $container_id jupyter lab build --minimize=False
          echo "running notebook"
          docker exec $container_id ls /home/jovyan/work
          docker exec $container_id jupyter execute /home/jovyan/work/test.ipynb >> ./output.txt
          sleep 5
          HEALTH=$(docker ps --format "{{.Names}}: {{.Status}}" | grep "stable" | awk '{print $2}')
          docker ps -a
          echo ""
          if [[ "$HEALTH" == "Up" ]]; then
          echo "container healthy"
          else
          echo ""
          cat ./output.txt
          exit -1
          fi
          echo ""
          echo "************SUCCESS***********"
      - name: Stop Docker container
        run: docker stop stable



  package-vers-test:
    needs: setup-and-build
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: image

      - name: pull image
        run: |
          IMAGE=$(cat image.txt)
          docker pull $IMAGE
      - name: checkout package versions
        run: |
          cp tests/version-check.py ./version-check.py #add python script to compare vers to this file 
          cp tests/versions.txt ./versions.txt #add correct version list to compare against
          chmod +x ./version-check.py # change perms to execute 
          IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | head -n 1) #get image name
          docker run -d --name stable $IMAGE
          sleep 7 # let properly start
          ID=$( docker ps -aqf "name=stable" )
          docker exec stable pip list >> ./list.txt #get rid of header for python comparison test
          tail -n +3 ./list.txt > temp.txt
          mv ./temp.txt ./list.txt #rewrite truncated list to file
          python3 version-check.py ./list.txt versions.txt #send to python for checking
          docker stop stable
  
  checksum:
    needs: setup-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: run checksum
        run: |
          make -C tests checksum-test

  size-time:
    needs: setup-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: image

      - name: Download time
        uses: actions/download-artifact@v2
        with:
          name: time

      - name: pull image
        run: |
          #IMAGE=$(cat image.txt)
          #docker pull $IMAGE 
          make pull-beta

      - name: extract size and display time and size
        run: |
          IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | head -n 1)
          echo "$IMAGE"
          docker run -d --name stable $IMAGE 
          SIZE=$( docker images --format "{{.Size}}" $IMAGE ) #extract size from running image
          echo ""
          echo ""
          cat time.txt #display calced time
          echo "" 
          echo "IMAGE SIZE:  $SIZE" #display size in GB
          echo ""
          docker stop stable


  UI-Test:
    runs-on: ubuntu-latest #use the latest ubuntu container image
    needs: setup-and-build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        
      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get upgrade chromium-browser

      - name: Installing necessary python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          pip install --upgrade selenium
          pip install --upgrade webdriver_manager
          chromedriver --version

      - name: Pull beta-version
        run: |
          make pull-beta

      - name: Run JupyterLab inside container
        run: |
          make run-beta &
          sleep 3

      - name: Run RISE extension tests
        run: |
          make -C tests rise-test
      
      - name: Run Screenshots difference tests
        run: |
          make -C tests screenshots-test